# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20bbbe3c7adbfea574d79ae1e902440a4dc8c455c89e16c1d4158d12a6d40b5897ff3be1e34e0d15f6090a02e85006e44380e55ae46be3a64ccd019ac3a6a3f4

test:
  secret_key_base: e14f7a3ee88aa63a45156a3545ae37c9b854b5c0dbbdfb6c41465c3c34988ef2eb9cbabc03adcea5086c7f483eb83daa39c0a225e59c7da4ca4ba56c113d2c5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
